### ISSUE TITLE
Tab box component for CDS

### ISSUE THREAD

**Issue by abby-lammers** [Chicago/design-cds-bootstrap#13]
The current chicago.gov website utilizes tab boxes (image below). Tab boxes are not part of the USWDS because accordions, which are part of the USWDS, have a similar functionality. 

Assuming that we want to build out a tab box for the CDS, here are some resources to help ensure that those tab boxes are accessible:
[whatsock examples](http://whatsock.com/tsg/#aria-tabs)
[W3 guidance](https://www.w3.org/TR/wai-aria-practices/#tabpanel)
[bootstrap tab navigation accessibility guidelines](https://getbootstrap.com/docs/4.0/components/navs/#regarding-accessibility)

![current chicago.gov tab box](https://user-images.githubusercontent.com/26829620/64815345-f7abec80-d56a-11e9-9d18-c9f63363e6a3.png)

**Comment by jdkunesh** [comment]
This is no longer valid given our conversion to Bootstrap.
