### ISSUE TITLE
Update side navigation style in CDS codebase

### ISSUE THREAD

**Issue by abby-lammers** [Chicago/design-cds-bootstrap#14]
See Figma: https://www.figma.com/file/g9vsh5gXm99OgZR4OGiOIm/Chicago-Design-System-Component-Library-sticker-sheet?node-id=0%3A1

![image](https://user-images.githubusercontent.com/26829620/64815274-c2070380-d56a-11e9-8e9f-be66b1eeb2d1.png)

**Comment by mario-duran** [comment]
I have this part almost complete (In progress). I used as reference the current uswds implementation.

**Comment by mario-duran** [comment]
Just fixed the mega-menu and sub-menu styles
