### ISSUE TITLE
Update form and form template styles in CDS codebase

### ISSUE THREAD

**Issue by abby-lammers** [Chicago/design-cds-bootstrap#17]
See Figma: https://www.figma.com/file/g9vsh5gXm99OgZR4OGiOIm/Chicago-Design-System-Component-Library-sticker-sheet?node-id=0%3A1

![image](https://user-images.githubusercontent.com/26829620/64814471-25903180-d569-11e9-9803-bec17637fd55.png)

**Comment by jdkunesh** [comment]
Review field length and field design best practices and update the Figma file with the new styles.

**Comment by alaeder16** [comment]
Some of the recommendations from best practices:

-Present Fields in a Single Column Layout. 
- Match the sizes of your form controls to the Bootstrap grid column sizes
- Match Fields to the Size of the Input
- Place Labels Above the Corresponding Input Fields

**Comment by alaeder16** [comment]
add tooltips

**Comment by jdkunesh** [comment]
Add tool tips to this document @alaeder16, please, and the preview as well.

**Comment by alaeder16** [comment]
what is preview?

**Comment by jdkunesh** [comment]
derp, I have no clue. @mario-duran, when you have tooltips in the codebase that map to @alaeder16's work, please close this card. I could not find evidence of it in the demo site.
