### ISSUE TITLE
Add/Update alert styles in CDS codebase

### ISSUE THREAD

**Issue by abby-lammers** [Chicago/design-cds-bootstrap#19]
Alert styles are in the [CDS figma sticker sheet](https://www.figma.com/file/g9vsh5gXm99OgZR4OGiOIm/Chicago-Design-System-Component-Library-sticker-sheet?node-id=0%3A1) and the styles need to be added to the CDS codebase or modified from the [current USWDS versions.](https://designsystem.digital.gov/components/alert/)

![image](https://user-images.githubusercontent.com/26829620/64813852-ef9e7d80-d567-11e9-88ae-72bb066d811b.png)

## A note on toasts (desktop alerts)

![image](https://user-images.githubusercontent.com/26829620/64813610-5cfdde80-d567-11e9-94ee-24d9eafee5b6.png)

Toast notifications are common in Bootstrap and other design systems, but aren't included in USWDS or CDS at this point. In this early version of the CDS, there is no reason to use toasts-- just use the alert format. If it becomes clear that toasts are necessary to include in CDS, be sure to follow accessibility guidelines. [Sheri Byrne-Haber's medium post](https://medium.com/@sheribyrnehaber/designing-toast-messages-for-accessibility-fb610ac364be) is a good starting place.

**Comment by jdkunesh** [comment]
- [x] Update visual alert styles to comport with Chicago Design System work.
- [x] We will not create a toast in v1.0.

**Comment by mario-duran** [comment]
Published the alerts implementation and added an example in the main page.
