### ISSUE TITLE
Accordion component

### ISSUE THREAD

**Issue by abby-lammers** [Chicago/design-cds-bootstrap#20]
The CDS needs a version of the [USWDS accordion component](https://designsystem.digital.gov/components/accordion/) that has been updated to use CDS colors and fonts. Be sure to consider the accessibility guidelines listed in the USWDS component documentation.

**Comment by jdkunesh** [comment]
- [ ] investigate accordion iconography

**Comment by alaeder16** [comment]
@mario-duran  I need to see what is the option available in bootstrap and then I can add it in Figma

**Comment by jdkunesh** [comment]
- [x] add component to kitchen sink page
- [ ] update in figma
