### ISSUE TITLE
UI -Header nav component

### ISSUE THREAD

**Issue by abby-lammers** [Chicago/design-cds-bootstrap#21]
- [x] Review Figma file & bootstrap default styles
- [x] Update Figma to reflect CDS colors & look, Bootstrap functionality
- [x] Update CDS-bootstrap codebase for new component
- [ ] Update Frontify UI codebase

## Logo v1 parts

- [ ] blue box, red star, CHICAGO in text, Mayor Lori E. Lightfoot as subtext
- [x] mobile-friendly: It should shrink effectively at mobile sizes.

## navigation review

- [x] review headers in Figma
- [x] review headers in bootstrap
- [ ] choose the bootstrap components that map most effectively to CDS versions

## follow on

- [x] update Figma mobile, tablet & desktop component views.

See Figma https://www.figma.com/file/g9vsh5gXm99OgZR4OGiOIm/Chicago-Design-System-Component-Library-sticker-sheet?node-id=158%3A1374

## Desktop headers

![image](https://user-images.githubusercontent.com/26829620/64812957-e3192580-d565-11e9-9368-089598865af3.png)

## Mobile headers

![image](https://user-images.githubusercontent.com/26829620/64813000-fa581300-d565-11e9-919c-632f20db5c62.png)

**Comment by jdkunesh** [comment]
<img width="338" alt="Screen Shot 2019-09-12 at 4 39 21 PM" src="https://user-images.githubusercontent.com/157725/64823023-f8994a00-d57b-11e9-91b8-0b8bc5cf10ba.png">
These files are found here in the repo. There are other implementations (alpha.chicago.gov, for example) that have a hacked together but working version of search.

**Comment by mario-duran** [comment]
The header is already implemented in the new code base and can be seen here: https://chicago.github.io/design-cds-bootstrap/ . 
We would like to review it and do sign off before moving it to Frontify
