### ISSUE TITLE
Update footers component

### ISSUE THREAD

**Issue by abby-lammers** [Chicago/design-cds-bootstrap#22]

**Comment by jdkunesh** [comment]
We have other work floating out there from DePaul & others to review prior to implementing this.

**Comment by mario-duran** [comment]
Added the footer to the cds-reference page,  fixed the responsive alignment and it works as expected now. We need to update Figma because we are now using the light-gray background

**Comment by alaeder16** [comment]
There is an older version frame exist in Figma - Let me know if we need to remove it completely to avoid confusion
