### ISSUE TITLE
UI - Top bar: New component, "this is a city of chicago site"

### ISSUE THREAD

**Issue by jdkunesh** [Chicago/design-cds-bootstrap#24]
- [x] convert this to a bootstrap component

<img width="1016" alt="Screen Shot 2019-11-12 at 9 30 25 AM" src="https://user-images.githubusercontent.com/157725/68685030-1741a000-052f-11ea-8f5f-8bab5aadfde4.png">

**Comment by alaeder16** [comment]
@mario-duran - I added it to figma. @jdkunesh - Do we have an icon library or do we need to create these two icons?

**Comment by jdkunesh** [comment]
Thanks @alaeder16!

@mario-duran @chrisjcalderon You had some recommendations of which icon systems Bootstrap currently has available. I would like to base the system UI icons off whatever's already there.

For these two graphics, for now it's fine to use what's there. We can shake out and refine items like this once we have given everything a good once over, I believe.

**Comment by alaeder16** [comment]
OK,  will provide the graphics. @jdkunesh - Do we use SVG or PNG files?

**Comment by jdkunesh** [comment]
¯\_(ツ)_/¯
Those two items are a couple SVGs currently, that works for me?

**Comment by dpmesa** [comment]
In several of the webapps we use fontawesome icons -see example below. They are easy to use/include and there is a decent number of icon available (1544) on the free version gallery: https://fontawesome.com/icons?d=gallery&m=free

<i class="icon fas fa-question-circle"></i>

![image](https://user-images.githubusercontent.com/12786488/68897425-178a9880-06f3-11ea-9bf5-92abc5de8f06.png)

**Comment by jdkunesh** [comment]
that works for me.

**Comment by alaeder16** [comment]
@dpmesa @jdkunesh  @mario-duran  - ok we can use font awesome however some icons will not be available in that exact format. I can replace with the similar and get it for your review.

**Comment by jdkunesh** [comment]
@dpmesa @alaeder16 @mario-duran Also, Big Shoulders Display & Text are now available in all Google Docs, so should be available in Figma natively as well.

Thanks!

j

**Comment by alaeder16** [comment]
yes! I saw it :). @jdkunesh  I have couple of items:
1. for the instance when we have cancel | submit action buttons we need to define color for the primary and secondary. Per USWDS - to use secondary for the previous step. However the cancel or clear are not prev. steps. Should we use base grey button in this case?
2. For the apps we are working on we using banner in some cases. I waht to make sure we have standards put in place for that. Here is the suggested:
https://federalist-proxy.app.cloud.gov/preview/uswds/uswds/release-2.2.1/components/preview/layout--landing.html.  Should we create section in figma for the visual elements like banner, images, etc?

**Comment by jdkunesh** [comment]
cool!

1. I would use Submit as the primary and Cancel as the secondary, so each would start out as the first item in the two rows below. Grey would only appear for disabled states.

<img width="671" alt="Screen Shot 2019-11-15 at 2 29 59 PM" src="https://user-images.githubusercontent.com/157725/68973645-6f3d0880-07b4-11ea-80c4-8d669f45f62f.png">

2. We definitely should create sections for these. We use that element on occasion today, and it's certainly there in the USWDS as you say. I would add this particular component as an issue for us to consider in our sprint planning: do we want to carry this one forward or look at the carousel component in Bootstrap and base a standard off that? For now, I would love to make sure we have headers squared away.

thanks @alaeder16! TGIF!

**Comment by alaeder16** [comment]
OK Roger that.



Sent from my Samsung Galaxy smartphone.


-------- Original message --------

**Comment by mario-duran** [comment]
This item is now included in the new code base and it is available here:
https://chicago.github.io/design-cds-bootstrap/
