### ISSUE TITLE
UI - Update link & button colors that use Flag Blue

### ISSUE THREAD

**Issue by jdkunesh** [Chicago/design-cds-bootstrap#25]
Today we often use Flag Blue with white text, or Flag Blue text on a white background. These are not accessible and should be changed.

Please:

- [x]  review the Figma sticker sheet and update instances of Flag Blue links or buttons, replacing them with Bahama or Malibu Blue (#005b99 or #0075BB)
- [x] review Bootstrap code, to ensure these changes are aligned.

**Comment by alaeder16** [comment]
@jdkunesh  Just to be clear - I will bring the Malibu up to the Primary colors and then will apply to all the links or buttons. Also we need to add the color reference name to the styles. And one more - we are not referencing the US web styles, correct? As soon I'm done with re-skinning it in figma  @mario-duran  will make adjustments to the code.

**Comment by jdkunesh** [comment]
Hi @alaeder16–

Yes. @mario-duran please work with Anna to add the color reference names as mentioned, both in Bootstrap & on her work in Figma.

Let's put Flag blue in a separate category: Primary, Secondary, Heraldry. Flag Red & Blue should go in Heraldry. Eventually we would add the Seal colors as well.

I am not sure what you mean by referencing the styles? The work now should be to port the UDWDS style/design choices to the equivalent Bootstrap component, feel free to give me a call or hit me up in Teams or what not to chat. Thanks!!

**Comment by alaeder16** [comment]
@jdkunesh 10-4

**Comment by alaeder16** [comment]
@mario-duran  I updated the Figma. Please use it as color reference in Bootstrap.

**Comment by mario-duran** [comment]
Perfect, I will @alaeder16

**Comment by mario-duran** [comment]
Updated all the colors in the variables.scss and made sure it matches as expected
