### ISSUE TITLE
class text-white has an incorrect name

### ISSUE THREAD

**Issue by chrisjcalderon** [Chicago/design-cds-bootstrap#26]
Somehow the text-white class is not being compiled correctly and instead a class:

.text-#fff {
    color: #fff !important
}
is added to the dist output.

**Comment by jdkunesh** [comment]
Hi @chrisjcalderon-

Where are you seeing that? I don't have a /dist/ folder currently?

**Comment by chrisjcalderon** [comment]
@jdkunesh 

https://chicago.github.io/design-cds-bootstrap/

you will notice elements that with a text-white class don't show correctly

the gitub page uses this style
https://chicago.github.io/design-cds-bootstrap/assets/css/styles.css


![image](https://user-images.githubusercontent.com/2113945/68795963-96120800-0617-11ea-8ca9-483251511dde.png)

**Comment by jdkunesh** [comment]
Locally, I have no issues. It looks like an error in how SASS is being generated on the server. I also made some additional accommodations– pulling the latest v.4.3.1 tag of Bootstrap, etc.

Within 30 minutes we'll see how the server builds work.

<img width="1380" alt="Screen Shot 2019-11-13 at 1 38 59 PM" src="https://user-images.githubusercontent.com/157725/68798430-0a4eaa80-061c-11ea-889d-7bcd9f470b2a.png">

Locally, the SASS processes just fine. 🤔 

<img width="502" alt="Screen Shot 2019-11-13 at 12 41 34 PM" src="https://user-images.githubusercontent.com/157725/68798615-54d02700-061c-11ea-8130-a342ff733bfd.png">

**Comment by jdkunesh** [comment]
It looks like minification is introducing an error, as I am now able to reproduce this locally.
Thanks again for the catch!

**Comment by jdkunesh** [comment]
https://github.com/Chicago/design-cds-bootstrap/blob/master/_config.yml

Apparently, Jekyll doesn't like SASS Compressed for some reason.

For now, I went with SASS _compact_, which puts each rule on its own line. See 
https://sass-lang.com/documentation/cli/ruby-sass#style
I am not sure why compressed forces a different issue. My guess is that there is a character that is causing minification to error. ¯\_(ツ)_/¯

For now, it works and we can add an issue to investigate.
