### ISSUE TITLE
SASS minification issues

### ISSUE THREAD

**Issue by jdkunesh** [Chicago/design-cds-bootstrap#27]
When minifying SASS, an error is introduced when using 'Compressed.' For now, we are using 'Compact,' but it is inefficient by comparison.

See https://github.com/Chicago/design-cds-bootstrap/issues/26 for details.

**Comment by mario-duran** [comment]
@jdkunesh with the code refactor I made this issue is completely solved. I made the configuration change and now it works as expected.

https://github.com/Chicago/design-cds-bootstrap/commit/0307f62a51599f0b0483189a075dcbe13e957b6a
