### ISSUE TITLE
Log into GitLab and move over an initial set of distribution files for people to use in the CDN.

### ISSUE THREAD

**Issue by jdkunesh** [Chicago/design-cds-bootstrap#29]
- [x] favicon files
- [x] css files
- [x] image assets
- [ ] a default HTML template?

Happy to chat these thru. favicon files i am aware of:

  android-chrome-192x192.png
  android-chrome-256x256.png
  apple-touch-icon.png
  browserconfig.xml
  favicon-16x16.png
  favicon-32x32.png
  favicon.ico
  mstile-150x150.png
  safari-pinned-tab.svg
  site.webmanifest

**Comment by mario-duran** [comment]
I already sent the files to Diego to incorporate them in the CDN.

**Comment by dpmesa** [comment]
An initial version of the Chicago DS was deployed to the City's CDN @ https://webapps1.chicago.gov/cdn/chiwds-1.0.0

I will ask Fernando, who is working on a new version of the eFORMS app, to include it in the app so we can test it with an actual app.

**Comment by jdkunesh** [comment]
@dpmesa we should pull over:

android-chrome-192x192.png
android-chrome-256x256.png
apple-touch-icon.png
browserconfig.xml
favicon-16x16.png
favicon-32x32.png
favicon.ico
mstile-150x150.png
safari-pinned-tab.svg
site.webmanifest

from the default directory here: https://github.com/Chicago/design-cds-bootstrap

**Comment by mario-duran** [comment]
> @dpmesa we should pull over:
> 
> android-chrome-192x192.png
> android-chrome-256x256.png
> apple-touch-icon.png
> browserconfig.xml
> favicon-16x16.png
> favicon-32x32.png
> favicon.ico
> mstile-150x150.png
> safari-pinned-tab.svg
> site.webmanifest
> 
> from the default directory here: https://github.com/Chicago/design-cds-bootstrap

Just added them to the main CDN repository
