### ISSUE TITLE
Add a basic accessibility statement to the theme site & CDN distribution

### ISSUE THREAD

**Issue by jdkunesh** [Chicago/design-cds-bootstrap#30]
https://alpha.chicago.gov/accessibility is an example accessibility statement. In addition to a kitchen sink page, this could be a good sample file to provide in our distribution.

It's also a good example page for us, as a simple page with typesetting to layout.

**Comment by mario-duran** [comment]
Created a page with basic content structure to use as a reference and grow from here
https://chicago.github.io/design-cds-bootstrap/accesibility
