### ISSUE TITLE
UX- Header nav component 

### ISSUE THREAD

**Issue by alaeder16** [Chicago/design-cds-bootstrap#34]
Review Figma file & bootstrap default styles
Update Figma to reflect CDS colors & look, Bootstrap functionality
blue box, red star, CHICAGO in text, Mayor Lori E. Lightfoot as subtext
mobile-friendly: It should shrink effectively at mobile sizes.
review headers in Figma
update Figma mobile, tablet & desktop component views.

**Comment by chrisjcalderon** [comment]
Question for all:  As the navigation, footer and other USWDS elements are styled in boostrap:

Will the usa- class prefix be removed in favor of a coc class prefix or perpahs something more generic i.e. site-footer, site-nav, etc?

**Comment by mario-duran** [comment]
I like the idea of having a coc prefix to make sure the Chicago design
system styles do not interfere with any other style already in use.

Currently I am still using usa- in the EDS implementation but I was
thinking on changing that to cds- on this project.

Please let me know your thoughts

**Comment by chrisjcalderon** [comment]
cds should work well. Also, we need to use hierarchy as much as possible so we use things like

cds-nav-link, but instead .nav.cds-nav  li.nav-link { ...}  

it will make it  much more maintainable and easier to override when needed,

**Comment by alaeder16** [comment]
Figma is updated
