### ISSUE TITLE
Fork or clone https://github.com/juzraai/bootstrap4-test-page to use as part of our build process

### ISSUE THREAD

**Issue by jdkunesh** [Chicago/design-cds-bootstrap#35]
To enable faster builds of component pages, use this codebase to display all our components.

**Comment by mario-duran** [comment]
The project its already cloned into https://github.com/Chicago/cds-reference

@jdkunesh when you have time, please configure the environment for deployment. I already modified the _config.yml

**Comment by jdkunesh** [comment]
Ok, this site is now live here: https://chicago.github.io/cds-reference/

Should we kill/hide the kitchen sink page on design-cds-bootstrap and move references here?

**Comment by mario-duran** [comment]
I talked to Christian earlier this week and we believe that we should keep both alive for now

**Comment by chrisjcalderon** [comment]
Mario, let's sit tomorrow and customize a few things  I would like to modify the header, point to the cds boostrap libs and add a few custom sections.

**Comment by jdkunesh** [comment]
It may be good to have a couple different pages in this repo, one pointing to the CDN, one to the latest styles from design-cds-bootstrap?
