### ISSUE TITLE
top bar: new component busted in ipad tablet

### ISSUE THREAD

**Issue by jdkunesh** [Chicago/design-cds-bootstrap#40]
![thumbnail_IMG_1081](https://user-images.githubusercontent.com/157725/69757473-b31ffe00-1122-11ea-9d8d-2bdbfd4e7582.png)

**Comment by mario-duran** [comment]
Acknowledged. Will review on Safari, it works fine on Chrome and Firefox (tablet mode)

**Comment by chrisjcalderon** [comment]
Mario, it is an issue with the sag image icon on IOS - it is to large and for some reason it needs the height to be defined explicitly

add this to the css

.trust-seal-flag { 
max-height:25px;
}

**Comment by mario-duran** [comment]
Done, it should work now. @jdkunesh please review and let us now.

**Comment by chrisjcalderon** [comment]
Mario,

Can you also modify this ?  only the top and right - I need them set to zero, leave the rest of the class modifiers as is

.trust-seal-action::after {
	top:0;
	right:0; 		
}

**Comment by jdkunesh** [comment]
verified on ipad.
