### ISSUE TITLE
Bootstrap - using REM

### ISSUE THREAD

**Issue by chrisjcalderon** [Chicago/design-cds-bootstrap#41]
All,

After doing some research for using an measure approach that is easy to understand and and manage, I found the following, which I would like to use for CDS:

Set the default font size to 62.5% 
html {
    font-size: 62.5%;
}

Once we do this, we can know what the resulting font size in pixels will be:

1rem = 10px
1.5rem = 15px
3rem = 30px

and so on and so forth. This way if in figma a font-size is expressed in pixels (as is now), we can easily determine the correct REM settings in bootstrap.

Thoughts?

**Comment by mario-duran** [comment]
We made this change in our current version.
