### ISSUE TITLE
Review corner rounding of elements

### ISSUE THREAD

**Issue by chrisjcalderon** [Chicago/design-cds-bootstrap#42]
Review corner rounding of elements

**Comment by alaeder16** [comment]
Button radius set to 10, however in Bootstrap 4 the common border-radius: .25rem;
the fields also have border-radius: .25rem;

**Comment by chrisjcalderon** [comment]
Right now is set to .25rem => 2.5px. is that the correct setting?

**Comment by alaeder16** [comment]
It’s 4px

Kind regards,
Anna Laeder
Electronic Knowledge Interchange
33 W Monroe St. Suite 1050
Chicago, Illinois
alaeder@eki-consulting.com<mailto:alaeder@eki-consulting.com>
847-337-2288(cell )
[cid:image001.jpg@01D44ACB.1E80C8C0]

________________________________
