### ISSUE TITLE
Consider adding a button group for ESRI map applications

### ISSUE THREAD

**Issue by jdkunesh** [Chicago/design-cds-bootstrap#43]
In ESRI, there's a top bar component that is not a radio button, but it's a series of checkboxes (see upper right of this screenshot). We should consider up/down/depressed states for these buttons:

![Screen Shot 2019-11-26 at 3 23 21 PM](https://user-images.githubusercontent.com/157725/70177752-95154900-16a0-11ea-8d1f-e74131eab71a.png)

**Comment by mario-duran** [comment]
Yes, something like this:
https://angular-ui.github.io/bootstrap/#!#buttons

**Comment by jdkunesh** [comment]
https://webapps1int.chicago.gov/homefinder/

is the url of the app. you can see the component in the upper right corner.

**Comment by jdkunesh** [comment]
@mario-duran pinging on this. I don't see a component for this currently.

It's like the pagination example, but it needs an option where a user can depress two buttons at the same time.

**Comment by jdkunesh** [comment]
@mario-duran I don't believe our current button group supports multi-select.

Can we make an example that does this? Looking around the internet, it seems like a plugin may be required?

Thanks
