### ISSUE TITLE
assemble a bulleted list of items that can be easily updated on the current chicago.gov.

### ISSUE THREAD

**Issue by jdkunesh** [Chicago/design-cds-bootstrap#48]

**Comment by chrisjcalderon** [comment]
Potentially:

Header
Footer
Change background menu color to white
Change hover and active to #005B99 ?
maybe change primary color to #005B99

**Comment by jdkunesh** [comment]
We are going to move ahead with this work by sharing a visual.

**Comment by chrisjcalderon** [comment]
I have a draft version in QA that we can use as to show what we could do quick while we refresh the entire site

-- header

![image](https://user-images.githubusercontent.com/2113945/71845183-5e5e9400-308d-11ea-94b7-58178c1f162d.png)


--- footer

![image](https://user-images.githubusercontent.com/2113945/71845213-72a29100-308d-11ea-99f9-0254911b2735.png)
