### ISSUE TITLE
Include some sample content in the bootstrap theme site.

### ISSUE THREAD

**Issue by jdkunesh** [Chicago/design-cds-bootstrap#56]
Version 0.1

- [ ] investigate how to tag releases in github, add branching and tagging to our CDN build: figure out a cadence
- [x] publish to the cdn
- [x] build a simple jekyll example site that takes the cdn components.
- [ ] update docs for outside audiences.

## Simple site

- [x] landing page
- [x] 404
- [x] accessibility statement
- [ ] privacy policy (link to)
- [ ] contact us
- [x] content page
- [ ] grid layout
- [ ] open layout
- [ ] favicons
- [ ] default social shares

**Comment by himaniravella** [comment]
Does the simple site has a Form page ?

**Comment by mario-duran** [comment]
> Does the simple site has a Form page ?

@himaniravella We don't have a form template available yet. In the mean time you can go to the components site and look for the Form section there. https://chicago.github.io/cds-reference/#forms

**Comment by mario-duran** [comment]
Updated the pages that we already have a template for.

**Comment by jdkunesh** [comment]
Hi @mario-duran 

Reflecting on this, I believe we'll still need a completely separate repository which references all the CDN assets to test and make sure we have the right work and right items here. I'll update this issue and make a separate one. We can have a 404, accessibility, etc. for this project, but we'll still need aa separate repo people can just clone and use with all its CDN goodness.
