### ISSUE TITLE
So designers may easily use the system, let's stress test the components with a default prototype file

### ISSUE THREAD

**Issue by jdkunesh** [Chicago/design-cds-bootstrap#62]
We need to keep the sticker sheet file lean, as a sticker sheet. Let's start to remove the more complex elements like the 404 page to its own file, built from the components list. I tried doing this with a different file, and it makes me think we have some work to do.

https://github.com/Chicago/design-cds-bootstrap/issues/56

**Comment by alaeder16** [comment]
@jdkunesh, Just to make sure I'm on the right path - I've created a new project - default prototype file. Do you want me to move the 404, social media and start using this for other content samples?

**Comment by jdkunesh** [comment]
- [ ] 404 page
- [ ] accessibility statement
- [ ] double-check figma file together
