### ISSUE TITLE
emergency notification chicago.gov 311.chicago.gov mobile app: how to handle alert content across applications

### ISSUE THREAD

**Issue by jdkunesh** [Chicago/design-cds-bootstrap#64]
![image002](https://user-images.githubusercontent.com/157725/73184841-abf57c00-40e2-11ea-8275-7819c3be1ef8.jpg)

**Comment by jdkunesh** [comment]
@chrisjcalderon will check.

**Comment by chrisjcalderon** [comment]
There might be a way to output alerts, if any,  in JSON format to be consuming by external apps. The idea is to expose a custom alerts rendered using a link such as:
https://qa.chicago.gov/city/en.alerts.html

This is done in QA now for testing purposes.
