### ISSUE TITLE
Figure out our CDN migration move from GitHub to GitLab

### ISSUE THREAD

**Issue by jdkunesh** [Chicago/design-cds-bootstrap#65]
Always have latest and versions in a dependent folder.

- [x] how to publish GH to GL
- [x] version number v.0.9.0 for the first one.
- [x] work out a versioning strategy

**Comment by jdkunesh** [comment]
@SoftwareChicago can you work with @dpmesa to document how we're pulling from GitHub to GitLab? This would be helpful for @nicklucius to understand, too.

Thanks!

**Comment by jdkunesh** [comment]
@SoftwareChicago @dpmesa @mario-duran any update here? Thx!

**Comment by dpmesa** [comment]
@mario-duran : please create a user called svc_gitlab_mgmt (websupportenvironment@cityofchicago.org) so it can be used from the build process to get the "latest" version of the CDN.
