### ISSUE TITLE
consider focus state visual indicator style

### ISSUE THREAD

**Issue by jdkunesh** [Chicago/design-cds-bootstrap#66]
When you tab from element to element, how should it be highlighted?

Visit https://alpha.chicago.gov/ it's one way, https://chicago.github.io/design-cds-bootstrap/ it's another.

We're going to go with Dotted and Blue (combining them) unless @alaeder16 has different feedback.

**Comment by jdkunesh** [comment]
Ok–

Dotted and blue it is, please update figma & bootstrap accordingly, @alaeder16 & @mario-duran

**Comment by alaeder16** [comment]
done, I have it on text link, button and form element in Figma

**Comment by mario-duran** [comment]
Added a focus state to the code base and to the sample pages.

Please review @alaeder16 @jdkunesh
