### ISSUE TITLE
Modals for CDS

### ISSUE THREAD

**Issue by abby-lammers** [Chicago/design-cds-bootstrap#9]
Currently, I could not identify a place on chicago.gov where modal pop-up dialogs are used. The USWDS is not planning on including modals (https://github.com/uswds/uswds/issues/911). 

If modals are implemented in a future version of CDS, consider the following resources on modal use and accessibility:
[Is a modal right for your application? - Nielsen Norman Group](https://www.nngroup.com/articles/overuse-of-overlays/)
[W3 modal accessibility considerations](https://www.w3.org/TR/wai-aria-practices/examples/dialog-modal/dialog.html)
[Bootstrap modal accessibility considerations](https://getbootstrap.com/docs/4.0/components/modal/#accessibility)

**Comment by mario-duran** [comment]
Added 3 samples of modal in the CDS Reference page:

https://chicago.github.io/cds-reference/#modals
